name: omnicourse_audio_progress_bar
description: A progress bar widget to show or change the position of an audio stream.
version: 0.0.1
homepage: https://github.com/omnicourse/omnicourse_audio_progress_bar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/progress_thumb.png